name: klondike
description: Klondike Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.28.1
  flutter:
      sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flame_lint: ^1.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/